<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="CMLPT077" failures="0" tests="6" name="Runner.EquipmentOrder_TestCases" time="48.138" errors="2" timestamp="2020-07-21T23:23:36 IST" skipped="4">
  <testcase classname="Runner.EquipmentOrder_TestCases" name="createEqpOrder" time="7.523">
    <error message="Unrecognized field &quot;orderDate&quot; (class Pojo.CreateEquipmentOrder), not marked as ignorable (20 known properties: &quot;stcc&quot;, &quot;customerNumber&quot;, &quot;customerName&quot;, &quot;offlineStation&quot;, &quot;connectingCarrierSCAC&quot;, &quot;customerState&quot;, &quot;equipmentTypeCode&quot;, &quot;orderNumber&quot;, &quot;requestingUserID&quot;, &quot;offlineStateCode&quot;, &quot;guaranteeProgram&quot;, &quot;customerEmail&quot;, &quot;customerStationNumber&quot;, &quot;customerCity&quot;, &quot;phoneExtension&quot;, &quot;organization&quot;, &quot;phoneNumber&quot;, &quot;orderQuantity&quot;, &quot;destinationRoute&quot;, &quot;specialInstructions&quot;])
 at [Source: (String)&quot;{&quot;orderNumber&quot;:51021,&quot;orderDate&quot;:&quot;2020-07-21T17:52:53+00:00&quot;,&quot;firstLoadDate&quot;:&quot;2020-08-30T00:00:00+00:00&quot;,&quot;equipmentTypeCode&quot;:&quot;C1&quot;,&quot;numberOfCarsOrdered&quot;:100,&quot;revisedNumberOfCarsOrdered&quot;:100,&quot;numberOfCarsApplied&quot;:0}&quot;; line: 1, column: 35] (through reference chain: Pojo.CreateEquipmentOrder[&quot;orderDate&quot;])" type="com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException">
      <![CDATA[com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "orderDate" (class Pojo.CreateEquipmentOrder), not marked as ignorable (20 known properties: "stcc", "customerNumber", "customerName", "offlineStation", "connectingCarrierSCAC", "customerState", "equipmentTypeCode", "orderNumber", "requestingUserID", "offlineStateCode", "guaranteeProgram", "customerEmail", "customerStationNumber", "customerCity", "phoneExtension", "organization", "phoneNumber", "orderQuantity", "destinationRoute", "specialInstructions"])
 at [Source: (String)"{"orderNumber":51021,"orderDate":"2020-07-21T17:52:53+00:00","firstLoadDate":"2020-08-30T00:00:00+00:00","equipmentTypeCode":"C1","numberOfCarsOrdered":100,"revisedNumberOfCarsOrdered":100,"numberOfCarsApplied":0}"; line: 1, column: 35] (through reference chain: Pojo.CreateEquipmentOrder["orderDate"])
at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:61)
at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:855)
at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1206)
at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1592)
at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1570)
at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:299)
at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:156)
at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4482)
at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3434)
at com.fasterxml.jackson.databind.ObjectMapper$readValue$2.call(Unknown Source)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:136)
at io.restassured.internal.path.json.mapping.JsonPathJackson2ObjectDeserializer.deserialize(JsonPathJackson2ObjectDeserializer.groovy:47)
at io.restassured.path.json.mapping.JsonPathObjectDeserializer$deserialize.call(Unknown Source)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:128)
at io.restassured.internal.mapping.Jackson2Mapper.deserialize(Jackson2Mapper.groovy:58)
at io.restassured.mapper.ObjectMapper$deserialize$0.call(Unknown Source)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:128)
at io.restassured.internal.mapping.ObjectMapping.parseWithJackson2(ObjectMapping.groovy:204)
at io.restassured.internal.mapping.ObjectMapping$parseWithJackson2$1.callStatic(Unknown Source)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallStatic(CallSiteArray.java:55)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:197)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:217)
at io.restassured.internal.mapping.ObjectMapping.deserialize(ObjectMapping.groovy:57)
at io.restassured.internal.mapping.ObjectMapping$deserialize$0.call(Unknown Source)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
at io.restassured.internal.RestAssuredResponseOptionsGroovyImpl.as(RestAssuredResponseOptionsGroovyImpl.groovy:220)
at io.restassured.internal.RestAssuredResponseOptionsImpl.as(RestAssuredResponseOptionsImpl.java:166)
at Runner.EquipmentOrder_TestCases.createEqpOrder(EquipmentOrder_TestCases.java:46)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1510)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- createEqpOrder -->
  <system-out/>
  <testcase classname="Runner.EquipmentOrder_TestCases" name="afterSuite" time="40.615">
    <error message="javax.mail.AuthenticationFailedException: 535 5.7.3 Authentication unsuccessful [BMXPR01CA0061.INDPRD01.PROD.OUTLOOK.COM]
" type="java.lang.RuntimeException">
      <![CDATA[java.lang.RuntimeException: javax.mail.AuthenticationFailedException: 535 5.7.3 Authentication unsuccessful [BMXPR01CA0061.INDPRD01.PROD.OUTLOOK.COM]

at Utils.SendEmail.sendEmail(SendEmail.java:167)
at Utils.Report.getreport(Report.java:46)
at Runner.TestSuite.afterSuite(TestSuite.java:48)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:63)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:348)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:302)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:351)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: javax.mail.AuthenticationFailedException: 535 5.7.3 Authentication unsuccessful [BMXPR01CA0061.INDPRD01.PROD.OUTLOOK.COM]

at com.sun.mail.smtp.SMTPTransport$Authenticator.authenticate(SMTPTransport.java:965)
at com.sun.mail.smtp.SMTPTransport.authenticate(SMTPTransport.java:876)
at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:780)
at javax.mail.Service.connect(Service.java:388)
at javax.mail.Service.connect(Service.java:246)
at javax.mail.Service.connect(Service.java:195)
at javax.mail.Transport.send0(Transport.java:254)
at javax.mail.Transport.send(Transport.java:124)
at Utils.SendEmail.sendEmail(SendEmail.java:160)
... 21 more
]]>
    </error>
  </testcase> <!-- afterSuite -->
  <system-out/>
  <testcase classname="Runner.EquipmentOrder_TestCases" name="getOrderDetails">
    <skipped/>
  </testcase> <!-- getOrderDetails -->
  <system-out/>
  <testcase classname="Runner.EquipmentOrder_TestCases" name="listOfEO">
    <skipped/>
  </testcase> <!-- listOfEO -->
  <system-out/>
  <testcase classname="Runner.EquipmentOrder_TestCases" name="cancelEO">
    <skipped/>
  </testcase> <!-- cancelEO -->
  <system-out/>
  <testcase classname="Runner.EquipmentOrder_TestCases" name="editEqpOrder">
    <skipped/>
  </testcase> <!-- editEqpOrder -->
  <system-out/>
</testsuite> <!-- Runner.EquipmentOrder_TestCases -->
